CREATE TABLE IF NOT EXISTS public.platform_auth_security_policy (
  id text PRIMARY KEY CHECK (id = 'global'),
  otp_all_enabled boolean NOT NULL DEFAULT false,
  otp_whatsapp_enabled boolean NOT NULL DEFAULT false,
  otp_sms_enabled boolean NOT NULL DEFAULT false,
  otp_email_enabled boolean NOT NULL DEFAULT false,
  password_reauth jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_by text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.platform_auth_security_policy (id)
VALUES ('global')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.isp_admins
  ADD COLUMN IF NOT EXISTS auth_version integer NOT NULL DEFAULT 1;

CREATE TABLE IF NOT EXISTS public.superadmin_impersonation_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  target_admin_id bigint NOT NULL REFERENCES public.isp_admins(id) ON DELETE CASCADE,
  target_username text NOT NULL,
  actor_name text NOT NULL,
  reason text NOT NULL,
  started_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  ended_at timestamptz,
  ended_by text,
  source_ip text,
  user_agent text
);

CREATE INDEX IF NOT EXISTS superadmin_impersonation_sessions_active_idx
  ON public.superadmin_impersonation_sessions (id, target_admin_id, expires_at)
  WHERE ended_at IS NULL;

CREATE TABLE IF NOT EXISTS public.platform_auth_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_name text NOT NULL,
  action text NOT NULL,
  target_admin_id bigint,
  impersonation_session_id uuid REFERENCES public.superadmin_impersonation_sessions(id) ON DELETE SET NULL,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_ip text,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS platform_auth_audit_created_at_idx
  ON public.platform_auth_audit (created_at DESC);
CREATE INDEX IF NOT EXISTS platform_auth_audit_target_idx
  ON public.platform_auth_audit (target_admin_id, created_at DESC);

ALTER TABLE public.platform_auth_security_policy ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.superadmin_impersonation_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.platform_auth_audit ENABLE ROW LEVEL SECURITY;