import { Router, type IRouter } from "express";
import healthRouter from "./health";
import customersRouter from "./customers";
import plansRouter from "./plans";
import vouchersRouter from "./vouchers";
import hotspotVouchersRouter from "./hotspot-vouchers-route.js";
import hotspotBindingsRouter from "./hotspot-bindings-route.js";
import hotspotRoamingRouter from "./hotspot-roaming-route.js";
import hotspotLoyaltyRouter from "./hotspot-loyalty-route.js";
import transactionsRouter from "./transactions";
import routersRouter from "./routers-route";
import syncRouter from "./sync-route";
import vpnRouter from "./vpn-route";
import provisionRouter from "./provision-route";
import routerEnsureRouter from "./router-ensure-route";
import routerManualRouter from "./router-manual-route.js";
import mikrotikRouter from "./mikrotik-route";
import webhookRouter from "./webhook-route";
import logsRouter from "./logs-route.js";
import bridgeRouter from "./bridge-route.js";
import mpesaRouter from "./mpesa-route.js";
import settingsRouter from "./settings-route.js";
import superAdminAuthRouter from "./super-admin-auth-route.js";
import superAdminRoutersRouter from "./super-admin-routers-route.js";
import superAdminBillingRouter from "./super-admin-billing-route.js";
import apiAuthRouter from "./api-auth-route.js";
import registrationRouter from "./registration-route.js";
import vpnManagementRouter from "./vpn-management-route.js";
import adminPageVisibilityRouter from "./admin-page-visibility-route.js";
import dashboardPreferencesRouter from "./dashboard-preferences-route.js";
import typographyRouter from "./typography-route.js";
import pppoePortalRouter from "./pppoe-portal-route.js";
import storageGovernanceRouter from "./storage-governance-route.js";
import adminSettingsRouter from "./admin-settings-route.js";
import resellerRouter from "./reseller-route.js";
import portServicesRouter from "./port-services-route.js";
import billingRouter from "./billing-route.js";
import hotspotBrandingRouter from "./hotspot-branding-route.js";
import whatsappRouter from "./whatsapp-route.js";
import smsRouter from "./sms-route.js";
import routerLoadBalancingRouter from "./router-load-balancing-route.js";
import platformEmailRouter from "./platform-email-route.js";
import routerMigrationsRouter from "./router-migrations-route.js";
import routerUserSnapshotsRouter from "./router-user-snapshots-route.js";
import platformAuthSecurityRouter from "./platform-auth-security-route.js";
import platformPageAuthRouter from "./platform-page-auth-route.js";
import superAdminAccountAccessRouter from "./super-admin-account-access-route.js";
import superAdminAdminsRouter from "./super-admin-admins-route.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(customersRouter);
router.use(plansRouter);
router.use(vouchersRouter);
router.use(hotspotVouchersRouter);
router.use(hotspotBindingsRouter);
router.use(hotspotRoamingRouter);
router.use(hotspotLoyaltyRouter);
router.use(transactionsRouter);
router.use(routersRouter);
router.use(syncRouter);
router.use(vpnRouter);
router.use(provisionRouter);
router.use(routerEnsureRouter);
router.use(routerManualRouter);
router.use(mikrotikRouter);
router.use(webhookRouter);
router.use(logsRouter);
router.use(bridgeRouter);
router.use(mpesaRouter);
router.use(settingsRouter);
router.use(superAdminAuthRouter);
router.use(superAdminRoutersRouter);
router.use(superAdminBillingRouter);
router.use(apiAuthRouter);
router.use(registrationRouter);
router.use(vpnManagementRouter);
router.use(adminPageVisibilityRouter);
router.use(dashboardPreferencesRouter);
  router.use(typographyRouter);
  router.use(pppoePortalRouter);
  router.use(storageGovernanceRouter);
  router.use(adminSettingsRouter);
  router.use(resellerRouter);
  router.use(portServicesRouter);
  router.use(billingRouter);
  router.use(hotspotBrandingRouter);
  router.use(whatsappRouter);
  router.use(smsRouter);
  router.use(routerLoadBalancingRouter);
  router.use(platformEmailRouter);
  router.use(routerMigrationsRouter);
  router.use(routerUserSnapshotsRouter);
  router.use(platformAuthSecurityRouter);
  router.use(platformPageAuthRouter);
  router.use(superAdminAccountAccessRouter);
  router.use(superAdminAdminsRouter);

export default router;
