import "./_group.css";
import { useMemo, useState, type CSSProperties, type ReactNode } from "react";
import {
  Activity, ArrowUpRight, Banknote, BarChart3, CalendarDays, CircleAlert,
  CircleCheck, CreditCard, Eye, EyeOff, Landmark, MessageSquare, ReceiptText,
  Router, Server, Signal, SlidersHorizontal, TrendingUp, Users, Wifi, WifiOff, X,
} from "lucide-react";

/**
 * Extracted baseline from the production admin Dashboard.  Network, billing,
 * auth, Supabase, wouter and preference contexts are intentionally fixture/no-op
 * boundaries for the isolated mockup.
 */
const routers = [
  { id: 1, name: "Nairobi-Core", host: "102.68.77.12", status: "online", model: "hEX S", ros_version: "7.14.2", last_seen: "2025-07-25T09:42:00Z" },
  { id: 2, name: "Westlands-AP", host: "10.10.0.2", status: "online", model: "RB4011", ros_version: "7.13.5", last_seen: "2025-07-25T09:40:00Z" },
  { id: 3, name: "Kasarani-Node", host: "10.10.0.7", status: "offline", model: "hAP ac²", ros_version: "7.12", last_seen: "2025-07-24T18:42:00Z" },
];
const customers = [
  ...Array.from({ length: 58 }, (_, i) => ({ id: i + 1, type: "hotspot", status: "active", created_at: `2025-${String((i % 7) + 1).padStart(2, "0")}-12T08:00:00Z`, expires_at: null })),
  ...Array.from({ length: 24 }, (_, i) => ({ id: i + 59, type: "pppoe", status: i === 22 ? "expired" : "active", created_at: `2025-${String((i % 7) + 1).padStart(2, "0")}-19T08:00:00Z`, expires_at: i === 22 ? "2025-06-01T00:00:00Z" : null })),
  ...Array.from({ length: 9 }, (_, i) => ({ id: i + 83, type: "static", status: "active", created_at: `2025-${String((i % 7) + 1).padStart(2, "0")}-23T08:00:00Z`, expires_at: null })),
];
const transactions = [
  { id: 1042, reference: "SFK92XQ71P", amount: 1500, payment_method: "mpesa", status: "completed", created_at: "2025-07-25T08:10:00Z" },
  { id: 1041, reference: "SFK88LM20T", amount: 500, payment_method: "mpesa", status: "completed", created_at: "2025-07-25T07:44:00Z" },
  { id: 1040, reference: "SFK71AB93K", amount: 2999, payment_method: "mpesa", status: "completed", created_at: "2025-07-24T21:03:00Z" },
  { id: 1039, reference: "STR-8842", amount: 1200, payment_method: "card", status: "pending", created_at: "2025-07-24T18:31:00Z" },
  { id: 1038, reference: "SFK55QW18Z", amount: 750, payment_method: "mpesa", status: "completed", created_at: "2025-07-24T16:22:00Z" },
];
const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const money = (n: number) => `KSh ${n.toLocaleString("en-KE")}`;

function Link({ children, className = "", href = "#" }: { children: ReactNode; className?: string; href?: string }) {
  return <a href={href} className={className} onClick={(e) => e.preventDefault()}>{children}</a>;
}
function KpiCard({ label, value, icon, tone }: { label: string; value: string; icon: ReactNode; tone: string }) {
  return <article className={`dashboard-kpi dashboard-kpi--${tone}`}><div className="dashboard-kpi-icon">{icon}</div><div className="dashboard-kpi-copy"><div className="dashboard-kpi-label">{label}</div><div className="dashboard-kpi-value">{value}</div></div></article>;
}
function StatMiniCard({ label, value, icon, tone }: { label: string; value: string; icon: ReactNode; tone: string }) {
  return <Link href="#" className={`dashboard-stat dashboard-stat--${tone}`}><span className="dashboard-stat-icon">{icon}</span><span className="dashboard-stat-copy"><span className="dashboard-stat-label">{label}</span><span className="dashboard-stat-value">{value}</span></span><ArrowUpRight className="dashboard-stat-arrow" size={15} /></Link>;
}
function DonutChart({ insights }: { insights: { label: string; count: number; color: string }[] }) {
  const total = insights.reduce((a, b) => a + b.count, 0), radius = 55, circumference = 2 * Math.PI * radius;
  let offset = 0;
  return <svg className="donut-chart" viewBox="0 0 160 160" role="img" aria-label={`${total} total users`}><circle cx="80" cy="80" r={radius} fill="none" stroke="var(--isp-border)" strokeWidth="20" />{insights.map((item) => { const dash = item.count / total * circumference; const current = <circle key={item.label} cx="80" cy="80" r={radius} fill="none" stroke={item.color} strokeWidth="20" strokeDasharray={`${dash} ${circumference - dash}`} strokeDashoffset={-offset + circumference * .25} style={{ transform: "rotate(-90deg)", transformOrigin: "80px 80px" }} />; offset += dash; return current; })}<text x="80" y="75" textAnchor="middle" fill="var(--isp-text)" fontSize="18" fontWeight="700">{total}</text><text x="80" y="94" textAnchor="middle" fill="var(--isp-text-muted)" fontSize="10">Total users</text></svg>;
}

function PlatformBillingBanner() {
  const [phone, setPhone] = useState("0712 345 678");
  const [message, setMessage] = useState("");
  return <section role="status" className="platform-billing-banner">
    <div><strong>Platform renewal due</strong><span>KSh 2,500 due by 31 Jul. Time left: <strong>5d 4h 20m</strong></span><small>{message || "Renewal payments are unavailable in this preview."}</small></div>
    <div className="platform-billing-actions"><input value={phone} onChange={(e) => setPhone(e.target.value)} aria-label="M-Pesa phone number" placeholder="07xx xxx xxx" /><button type="button" onClick={() => setMessage("Payment prompt simulated in this preview.")}>Renew</button></div>
  </section>;
}

export function ExtractedCurrent() {
  const [selectedRouter, setSelectedRouter] = useState<number | "all">("all");
  const [hideAmounts, setHideAmounts] = useState(false);
  const onlineRouters = routers.filter((r) => r.status === "online").length;
  const visibleRouters = selectedRouter === "all" ? routers : routers.filter((r) => r.id === selectedRouter);
  const insights = [{ label: "Hotspot", count: 58, color: "var(--dashboard-accent, var(--isp-accent))" }, { label: "PPPoE", count: 24, color: "#8879b7" }, { label: "Static", count: 9, color: "var(--isp-green)" }];
  const monthly = useMemo(() => MONTHS.map((month, i) => ({ month, count: customers.filter((c) => new Date(c.created_at).getMonth() === i).length })), []);
  const maxCount = Math.max(...monthly.map((m) => m.count), 1);
  return <div className="admin-shell isp-mock">
    <aside className="admin-sidebar admin-sidebar--open" style={{ width: 240 }}>
      <div className="sidebar-logo"><div className="sidebar-logo-inner"><div className="sidebar-logo-icon"><Router size={16} /></div><div><div className="sidebar-brand-name">Ochola SuperNet</div><div className="sidebar-brand-sub">Admin Panel</div></div></div><button className="sidebar-close-btn" type="button"><SlidersHorizontal size={14} /></button></div>
      <nav className="sidebar-nav">{["Overview", "Customers", "Billing", "Network", "Tools", "Admin"].map((section) => <div className="nav-section" key={section}><div className="nav-section-label">{section}</div><div className={`nav-row ${section === "Overview" ? "nav-row--active" : ""}`}><span className="nav-icon"><Activity size={14} /></span><span className="nav-label">{section === "Overview" ? "Dashboard" : section}</span></div></div>)}</nav>
      <div className="sidebar-user"><div className="sidebar-avatar">A</div><div className="sidebar-user-info"><div className="sidebar-user-name">Administrator</div><div className="sidebar-user-status"><span className="status-dot" /> Online</div></div></div>
    </aside>
    <div className="admin-main"><header className="admin-header admin-header--dark"><button className="header-btn" type="button"><SlidersHorizontal size={16} /></button><div className="header-search"><span className="header-search-icon">⌕</span><input className="header-search-input" placeholder="Search customers, routers…" /><kbd className="header-search-kbd">⌘K</kbd></div><div className="header-spacer" /><div className="header-actions"><div className="header-live-pill"><span className="live-dot" /> LIVE</div><button className="header-btn" type="button"><BellIcon /></button><div className="header-user-pill"><div className="header-avatar">A</div><span className="header-user-name">Administrator</span></div></div></header>
      <main className="admin-content"><PlatformBillingBanner /><div className="dashboard-page" style={{ "--dashboard-accent": "#d96835" } as CSSProperties}>
        <header className="dashboard-hero"><div><div className="dashboard-eyebrow"><span className="dashboard-live-mark"><Activity size={12} /></span>Live operations</div><h1>Good morning, Administrator</h1><p>Network pulse, customer activity, and cashflow in one view.</p></div><div className="dashboard-date"><CalendarDays size={15} /> Friday, 25 July</div></header>
        <div className="dashboard-section-kicker">Financial pulse <span className="dashboard-section-meta">Updated from live payment activity</span><button className="dashboard-amount-toggle" type="button" onClick={() => setHideAmounts(!hideAmounts)}>{hideAmounts ? <Eye size={13} /> : <EyeOff size={13} />} {hideAmounts ? "Show amounts" : "Hide amounts"}</button></div>
        <section className="dashboard-kpi-grid"><KpiCard label="Income today" value={hideAmounts ? "••••" : money(2000)} icon={<Banknote size={19} />} tone="green" /><KpiCard label="Income this month" value={hideAmounts ? "••••" : money(48750)} icon={<TrendingUp size={19} />} tone="green" /><KpiCard label="Total transactions" value="128" icon={<ReceiptText size={19} />} tone="amber" /><KpiCard label="Total revenue" value={hideAmounts ? "••••" : money(152300)} icon={<BarChart3 size={19} />} tone="plum" /></section>
        <section className="dashboard-stat-grid"><StatMiniCard label="Total online users" value="37" icon={<Users size={16} />} tone="green" /><StatMiniCard label="PPPoE online" value="18" icon={<Wifi size={16} />} tone="accent" /><StatMiniCard label="Hotspot online" value="14" icon={<Signal size={16} />} tone="teal" /><StatMiniCard label="VLAN users online" value="3" icon={<Wifi size={16} />} tone="accent" /><StatMiniCard label="Static online" value="2" icon={<Server size={16} />} tone="amber" /><StatMiniCard label="Active / expired users" value="90/1" icon={<CircleCheck size={16} />} tone="green" /><StatMiniCard label="Active resellers" value="6" icon={<Users size={16} />} tone="accent" /><StatMiniCard label="Online resellers" value="4" icon={<Wifi size={16} />} tone="teal" /></section>
        <section className="gateway-strip"><span className="gateway-icon"><Landmark size={17} /></span><span className="gateway-copy"><strong>mpesapaybillstk</strong><span>M-Pesa PayBill</span></span><span className="isp-badge isp-badge-green"><CircleCheck size={12} /> Active</span><Link href="#" className="gateway-link">Manage gateway <ArrowUpRight size={13} /></Link></section>
        <div className="dashboard-section-kicker">Network health <span>Heartbeat window · 10 seconds</span></div>
        <section className="section-card dashboard-router-panel"><div className="panel-heading"><div className="panel-title"><span className="panel-title-icon"><Router size={16} /></span><div><h2>Router status</h2><p>Online only after a recent RouterOS API heartbeat</p></div></div><div className="panel-heading-meta"><span className="isp-badge isp-badge-green">{onlineRouters} online</span><span className="isp-badge isp-badge-red">{routers.length - onlineRouters} offline</span></div></div><div className="router-card-grid">{visibleRouters.map((router) => <article className={`router-card router-card--${router.status}`} key={router.id}><div className="router-card-topline"><span className="router-card-name">{router.name}</span><span className={`router-health router-health--${router.status}`}>{router.status === "online" ? <Wifi size={12} /> : <WifiOff size={12} />} {router.status === "online" ? "Online" : "Offline"}</span></div><div className="router-host">{router.host}</div><div className="router-meta">{router.model} · ROS v{router.ros_version}</div>{router.status === "offline" && <div className="router-seen">Last seen Yesterday 18:42</div>}</article>)}</div></section>
        <section className="router-filter-bar"><div className="router-filter-label"><SlidersHorizontal size={15} /> Filter by router</div><div className="router-filter-options">{[{ key: "all" as const, label: "All routers" }, ...routers.map((r) => ({ key: r.id, label: r.name }))].map((option) => <button type="button" key={String(option.key)} className={`router-filter-pill ${selectedRouter === option.key ? "router-filter-pill--active" : ""}`} onClick={() => setSelectedRouter(option.key)}>{option.label}</button>)}</div>{selectedRouter !== "all" && <div className="router-filter-selected">Showing <strong>{routers.find((r) => r.id === selectedRouter)?.name}</strong><button type="button" onClick={() => setSelectedRouter("all")}><X size={13} /></button></div>}</section>
        <div className="dashboard-main-grid"><section className="section-card chart-panel"><div className="panel-heading"><div className="panel-title"><span className="panel-title-icon panel-title-icon--soft"><Users size={16} /></span><h2>Registered customers</h2></div></div><div className="chart-body"><svg viewBox="0 0 600 180" className="bar-chart">{monthly.map((m, i) => <g key={m.month}><rect x={i * 49 + 5} y={150 - m.count / maxCount * 110} width="30" height={m.count / maxCount * 110} rx="3" fill="var(--dashboard-accent, var(--isp-accent))" opacity=".8" /><text x={i * 49 + 20} y="170" textAnchor="middle">{m.month}</text></g>)}</svg></div></section><section className="section-card insight-card"><div className="panel-heading"><h2>Users by access type</h2></div><div className="insight-content"><DonutChart insights={insights} /><div className="insight-legend">{insights.map((item) => <div className="insight-row" key={item.label}><span className="insight-swatch" style={{ background: item.color }} />{item.label}<strong>{item.count}</strong></div>)}</div></div></section></div>
        <section className="section-card" aria-label="Network telemetry overview"><div className="panel-heading"><div className="panel-title"><span className="panel-title-icon panel-title-icon--soft"><Activity size={16} /></span><div><h2>Network telemetry overview</h2><p>Live Hotspot leases and PPPoE sessions, filtered on the server</p></div></div><span className="panel-heading-meta">Updated 09:42</span></div><div className="dashboard-telemetry-filters"><label>Filter by router<select><option>All routers</option>{routers.map((r) => <option key={r.id}>{r.name}</option>)}</select></label><label>Filter by port<select><option>All physical ports</option><option>ether1</option><option>ether2</option></select></label><label>Filter by reseller<select><option>All resellers</option><option>Ochola Partners</option></select></label></div><div className="dashboard-telemetry-totals">{[{ label: "System-wide online users", value: 37, tone: "green" }, { label: "Active PPPoE sessions", value: 18, tone: "accent" }, { label: "Active Hotspot leases", value: 14, tone: "teal" }].map((item) => <div className={`dashboard-telemetry-total dashboard-telemetry-total--${item.tone}`} key={item.label}><span>{item.label}</span><strong>{item.value}</strong></div>)}</div><div style={{ overflowX: "auto" }}><table className="isp-table"><thead><tr><th>Physical port</th><th>Online</th><th>PPPoE</th><th>Hotspot</th><th>Router state</th></tr></thead><tbody>{routers.map((r) => <tr key={r.id}><td className="table-mono">ether{r.id}</td><td>12</td><td>6</td><td>5</td><td><span className={`isp-badge ${r.status === "online" ? "isp-badge-green" : "isp-badge-amber"}`}>{r.status === "online" ? "Available" : "Unavailable"}</span></td></tr>)}</tbody></table></div></section>
        <div className="dashboard-section-kicker">Customer activity <span>Registration trends and access mix</span></div>
        <div className="dashboard-main-grid"><section className="section-card chart-panel"><div className="panel-heading"><div className="panel-title"><span className="panel-title-icon panel-title-icon--soft"><Users size={16} /></span><h2>Registered customers</h2></div></div><div className="chart-body"><svg viewBox="0 0 600 180" className="bar-chart">{monthly.map((m, i) => <g key={m.month}><rect x={i * 49 + 5} y={150 - m.count / maxCount * 110} width="30" height={m.count / maxCount * 110} rx="3" fill="var(--dashboard-accent, var(--isp-accent))" opacity=".8" /><text x={i * 49 + 20} y="170" textAnchor="middle">{m.month}</text></g>)}</svg></div></section><section className="section-card insight-card"><div className="panel-heading"><h2>Users by access type</h2></div><div className="insight-content"><DonutChart insights={insights} /><div className="insight-legend">{insights.map((item) => <div className="insight-row" key={item.label}><span className="insight-swatch" style={{ background: item.color }} />{item.label}<strong>{item.count}</strong></div>)}</div></div></section></div>
        <div className="dashboard-section-kicker">Payment activity <span>Most recent subscriber transactions</span></div><section className="section-card transaction-panel"><div className="panel-heading"><div className="panel-title"><span className="panel-title-icon panel-title-icon--soft"><ReceiptText size={16} /></span><div><h2>Recent transactions</h2><p>Latest payment activity across subscribers</p></div></div><Link href="#" className="panel-link">View all <ArrowUpRight size={13} /></Link></div><div className="transaction-table-wrap"><table className="isp-table"><thead><tr>{["ID", "Reference", "Amount", "Method", "Status", "Date"].map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{transactions.map((tx) => <tr key={tx.id}><td className="table-mono">#{tx.id}</td><td className="table-mono">{tx.reference}</td><td className="table-amount">{money(tx.amount)}</td><td><span className="isp-badge isp-badge-blue">{tx.payment_method.toUpperCase()}</span></td><td><span className={`isp-badge ${tx.status === "completed" ? "isp-badge-green" : "isp-badge-amber"}`}>{tx.status}</span></td><td className="table-date">{new Date(tx.created_at).toLocaleString("en-KE", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" })}</td></tr>)}</tbody></table></div></section>
      </div></main></div>
  </div>;
}
function BellIcon() { return <MessageSquare size={15} />; }