// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hotspot-login/HotspotLoginVariants.tsx": () => import("../components/mockups/hotspot-login/HotspotLoginVariants.tsx"),
  "./components/mockups/dashboard-card-restyle/CurrentIspCards.tsx": () => import("../components/mockups/dashboard-card-restyle/CurrentIspCards.tsx"),
  "./components/mockups/dashboard-card-restyle/CurrentResellerCards.tsx": () => import("../components/mockups/dashboard-card-restyle/CurrentResellerCards.tsx"),
  "./components/mockups/dashboard-card-restyle/SolidIspCards.tsx": () => import("../components/mockups/dashboard-card-restyle/SolidIspCards.tsx"),
  "./components/mockups/dashboard-card-restyle/SolidResellerCards.tsx": () => import("../components/mockups/dashboard-card-restyle/SolidResellerCards.tsx"),
  "./components/mockups/isp-dashboard-extracted/Current.tsx": () => import("../components/mockups/isp-dashboard-extracted/Current.tsx"),
  "./components/mockups/isp-dashboard-extracted/Standardized.tsx": () => import("../components/mockups/isp-dashboard-extracted/Standardized.tsx"),
  "./components/mockups/isp-dashboard/Current.tsx": () => import("../components/mockups/isp-dashboard/Current.tsx"),
  "./components/mockups/isp-dashboard/EmeraldFinance.tsx": () => import("../components/mockups/isp-dashboard/EmeraldFinance.tsx"),
  "./components/mockups/isp-dashboard/ExecutiveNavy.tsx": () => import("../components/mockups/isp-dashboard/ExecutiveNavy.tsx"),
  "./components/mockups/isp-dashboard/SlateProfessional.tsx": () => import("../components/mockups/isp-dashboard/SlateProfessional.tsx"),
  "./components/mockups/migration-page/MigrationPage.tsx": () => import("../components/mockups/migration-page/MigrationPage.tsx")
};
