// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/isp-dashboard/Current.tsx": () => import("../components/mockups/isp-dashboard/Current.tsx"),
  "./components/mockups/isp-dashboard/EmeraldFinance.tsx": () => import("../components/mockups/isp-dashboard/EmeraldFinance.tsx"),
  "./components/mockups/isp-dashboard/ExecutiveNavy.tsx": () => import("../components/mockups/isp-dashboard/ExecutiveNavy.tsx"),
  "./components/mockups/isp-dashboard/SlateProfessional.tsx": () => import("../components/mockups/isp-dashboard/SlateProfessional.tsx")
};
