import test from "node:test";
import assert from "node:assert/strict";
import { build } from "esbuild";
import { readFile, rm } from "node:fs/promises";
import path from "node:path";

const outdir = "tests/.migration-build";
await build({ entryPoints: ["src/lib/router-migration-exporter.ts", "src/lib/router-migration-importer.ts", "src/lib/router-migration-export-script.ts", "src/lib/migration-tunnel.ts"], outdir, bundle: true, platform: "node", format: "cjs", outExtension: { ".js": ".cjs" }, external: ["node-routeros"], logLevel: "silent" });
const exporter = await import(path.resolve(outdir, "router-migration-exporter.cjs"));
const importer = await import(path.resolve(outdir, "router-migration-importer.cjs"));
const exportScript = await import(path.resolve(outdir, "router-migration-export-script.cjs"));
const tunnelScript = await import(path.resolve(outdir, "migration-tunnel.cjs"));
await rm(outdir, { recursive: true, force: true });

test("source allowlist excludes files and mutations", () => {
  assert.ok(exporter.SOURCE_PRINT_COMMANDS.every(x => x.endsWith("/print") && !x.startsWith("/file")));
  assert.doesNotThrow(() => exporter.assertSourceCommand("/system/routerboard/print"));
  assert.doesNotThrow(() => exporter.assertSourceCommand("/system/license/print"));
  assert.throws(() => exporter.assertSourceCommand("/file/print"));
  assert.throws(() => exporter.assertSourceCommand("/ip/address/add"));
});
test("downloadable helper is read-only and does not create a router file", () => {
  assert.match(exportScript.READ_ONLY_ROUTER_EXPORT_SCRIPT, /\/export show-sensitive terse/);
  assert.doesNotMatch(exportScript.READ_ONLY_ROUTER_EXPORT_SCRIPT, /file\s*=/i);
  assert.doesNotMatch(exportScript.READ_ONLY_ROUTER_EXPORT_SCRIPT, /\/file\//i);
  assert.doesNotMatch(exportScript.READ_ONLY_ROUTER_EXPORT_SCRIPT, /\/interface ovpn-client add/);
});
test("domain collector uses HTTP POST data chunks instead of unsupported HTTP file upload", () => {
  const script = exportScript.buildDomainRouterExportScript("https://isplatty.org/api/router-migrations/collector-upload?token=test");
  assert.match(script, /\/export show-sensitive terse file=\$exportFile/);
  assert.match(script, /http-method=post/);
  assert.match(script, /http-data=\$chunk/);
  assert.match(script, /chunkIndex/);
  assert.match(script, /https:\/\/isplatty\.org\/api\/router-migrations\/collector-upload\?token=test&chunk=/);
  assert.doesNotMatch(script, /\$safeUploadUrl/);
  assert.doesNotMatch(script, /upload=yes/);
  assert.doesNotMatch(script, /http-header-field="Content-Type: application\/octet-stream"/);
});
test("temporary tunnel script is address-bound and self-removing", () => {
  const script = tunnelScript.buildMigrationTunnelScript({
    endpoint: "vpn.example.test",
    port: 1194,
    username: "ochola-mig-1-abcd",
    password: "one-time-secret",
    tunnelIp: "10.8.0.42",
    interfaceName: "ochola-mig-1-abcd",
    firewallComment: "ochola-migration:42",
    schedulerName: "ochola-migration-expiry-42",
  });
  assert.match(script, /Expected router tunnel address: 10\.8\.0\.42/);
  assert.match(script, /:local migrationTunnelInterfaceName "ochola-mig-1-abcd"/);
  assert.match(script, /\/interface ovpn-client add name=\$migrationTunnelInterfaceName connect-to="vpn\.example\.test"/);
  assert.match(script, /temporary migration tunnel interface was not created/);
  assert.match(script, /interval=1h/);
  assert.match(script, /\/interface ovpn-client remove/);
  assert.match(script, /\/ip firewall filter remove/);
  assert.match(script, /dst-port=8728 src-address=10\.8\.0\.1 in-interface="ochola-mig-1-abcd"/);
  assert.doesNotMatch(script, /\/ip route add/);
});
test("collector export script stays separate from the connection script", () => {
  const script = exportScript.buildDomainRouterExportScript(
    "https://isplatty.org/api/router-migrations/collector-upload?token=test",
  );
  assert.match(script, /Run the separate migration-tunnel script first/);
  assert.match(script, /\/export show-sensitive terse file=\$exportFile/);
  assert.doesNotMatch(script, /\/interface ovpn-client add/);
  assert.doesNotMatch(script, /\/ip firewall filter add/);
  assert.doesNotMatch(script, /\/ip route add/);
});
test("terminal export parser keeps sensitive values server-side and maps portable sections", () => {
  const pkg = exporter.parseRouterOsExport(`
# generated by RouterOS
/ip pool
add name=customers ranges=10.0.0.2-10.0.0.254
/ppp profile
add name=basic rate-limit=10M/5M session-timeout=1h
/ppp secret
add name=alice password=secret profile=basic service=pppoe
`);
  assert.equal(pkg.ip_pools[0].name, "customers");
  assert.equal(pkg.ppp_profiles[0]["session-timeout"], "1h");
  assert.equal(pkg.ppp_secrets[0].password, "secret");
  assert.equal(pkg.raw_export, undefined);
});
test("export redacts secret fields and never reads files", async () => {
  const seen = [];
  const pkg = await exporter.exportRouterMigration({ host: "x", port: 8728, username: "u", password: "p" }, async c => {
    seen.push(c[0]); return [{ name: "a", password: "leak", private_key: "key" }];
  });
  assert.equal(pkg.interfaces[0].password, exporter.MANUAL);
  assert.equal(pkg.interfaces[0].private_key, exporter.MANUAL);
  assert.ok(!seen.some(x => x.startsWith("/file")));
});
test("dry run sends zero writes", async () => {
  const plan = importer.buildMigrationPlan({ ip_pools: [{ name: "p", ranges: "10.0.0.2-10.0.0.3" }] });
  let calls = 0;
  const r = await importer.executeMigrationPlan(plan, async () => { calls++; return []; }, ["ip_pools:0"], true);
  assert.equal(calls, 0); assert.equal(r.commands.length, 1);
});
test("source and target overlap is rejected", () => {
  assert.throws(() => importer.assertDistinctTargets({ id: 1, host: "a" }, { id: 2, host: "a" }));
});
test("only approved explicitly mapped entities are written", async () => {
  const plan = importer.buildMigrationPlan({ ip_pools: [{ name: "p", ranges: "a" }], queues: [{ name: "no" }] });
  const calls = [];
  await importer.executeMigrationPlan(plan, async c => { calls.push(c); return []; }, [], false);
  assert.equal(calls.filter(c => c[0].endsWith("/add")).length, 0);
  assert.equal(plan.unsupported[0].category, "queues");
});
test("import stops at first critical failure", async () => {
  const plan = importer.buildMigrationPlan({ ip_pools: [{ name: "p", ranges: "a" }], ppp_profiles: [{ name: "q" }] });
  const result = await importer.executeMigrationPlan(plan, async c => {
    if (c[0] === "/ip/pool/add") throw new Error("nope"); return [];
  }, ["ip_pools:0", "ppp_profiles:0"], false);
  assert.equal(result.stopped, true); assert.equal(result.applied.length, 0);
});
test("target state is redacted and persisted before the first write", async () => {
  const plan = importer.buildMigrationPlan({ ip_pools: [{ name: "p", ranges: "10.0.0.2-10.0.0.3" }] });
  const events = [];
  await importer.executeMigrationPlan(
    plan,
    async c => {
      events.push(c[0].endsWith("/print") ? "read" : "write");
      return c[0].endsWith("/print") ? [{ name: "existing", password: "must-not-persist" }] : [];
    },
    ["ip_pools:0"],
    false,
    async state => {
      events.push("persist");
      assert.equal(state.ip_pools[0].password, exporter.MANUAL);
    },
  );
  assert.deepEqual(events.slice(0, 3), ["read", "persist", "write"]);
});
test("local billing assets compile credentials and mapped reseller queues", () => {
  const plan = importer.buildMigrationPlan({
    local_assets: {
      plans: [{ id: 11, name: "Home 20", type: "pppoe", speed_down: 20, speed_up: 10 }],
      ppp_secrets: [{ username: "alice", password: "secret", profile: "home-20", ip_address: "10.0.0.10", port_id: 4 }],
      customers: [{ username: "alice", type: "pppoe", ip_address: "10.0.0.10", port_id: 4 }],
      hotspot_users: [],
    },
  }, {
    portMapping: [{ sourcePortId: 4, targetPortId: 9 }],
    targetPorts: [{ id: 9, interface_name: "ether4", reseller_id: 22, bandwidth_cap_mbps: 30 }],
  });
  const secret = plan.items.find(item => item.category === "local_ppp_secrets");
  const rootQueue = plan.items.find(item => item.category === "migration_queues" && item.command.includes("=name=RESELLER_ROOT_ether4"));
  const queue = plan.items.find(item => item.category === "migration_queues" && item.command.includes("=parent=RESELLER_ROOT_ether4"));
  assert.ok(secret);
  assert.ok(rootQueue);
  assert.ok(rootQueue.command.includes("=target=ether4"));
  assert.ok(rootQueue.command.includes("=max-limit=30M/30M"));
  assert.ok(secret.command.includes("=password=secret"));
  assert.ok(queue);
  assert.ok(queue.command.includes("=parent=RESELLER_ROOT_ether4"));
  assert.ok(queue.command.includes("=max-limit=30M/30M"));
  const stored = importer.redactMigrationPlan(plan);
  assert.ok(stored.items.every(item => !item.command.some(word => word === "=password=secret")));
  assert.ok(stored.items.some(item => item.command.includes("=password=REQUIRES_MANUAL_CONFIGURATION")));
});
test("approved named resources update instead of duplicating target rows", async () => {
  const plan = importer.buildMigrationPlan({ ip_pools: [{ name: "pool-a", ranges: "10.0.0.2-10.0.0.3" }] });
  const writes = [];
  await importer.executeMigrationPlan(plan, async command => {
    if (command[0] === "/ip/pool/print") return [{ ".id": "*1", name: "pool-a" }];
    writes.push(command);
    return [];
  }, ["ip_pools:0"], false);
  assert.equal(writes[0][0], "/ip/pool/set");
  assert.equal(writes[0][1], "=.id=*1");
});
test("database schema enforces one expiring lease per target router", async () => {
  const sql = await readFile("migrations/2026_router_migration_jobs.sql", "utf8");
  assert.match(sql, /target_router_id bigint primary key/);
  assert.match(sql, /on conflict \(target_router_id\) do nothing/);
  assert.match(sql, /expires_at <= now\(\)/);
  assert.match(sql, /renew_router_migration_target_lease/);
  assert.match(sql, /tunnel_lease_id bigint references router_migration_tunnel_leases/);
});
test("authenticated migration access is tenant-scoped", async () => {
  const route = await readFile("src/routes/router-migrations-route.ts", "utf8");
  assert.match(route, /router\.use\("\/router-migrations", requireAuth\(\)\)/);
  assert.doesNotMatch(route, /router\.use\("\/router-migrations", requireAdmin\(\)\)/);
  assert.match(route, /isp_routers", `id=eq\.\$\{id\}\$\{ownerFilter\}&select=/);
  assert.match(route, /router_migration_jobs", `id=eq\.\$\{id\}\$\{ownerFilter\}&select=/);
  assert.match(route, /admin_id=eq\.\$\{adminId\}/);
});
test("migration browser API uses the signed-in session without tenant headers", async () => {
  const api = await readFile("../ochola-supernet/src/pages/admin/network/migration/api.ts", "utf8");
  assert.match(api, /Authorization: `Bearer \$\{token\}`/);
  assert.doesNotMatch(api, /X-Impersonated-Admin-Id/);
});
test("collector handoff requires the authenticated RouterOS preflight", async () => {
  const route = await readFile("src/routes/router-migrations-route.ts", "utf8");
  assert.equal((route.match(/if \(!tunnel \|\| tunnel\.status !== "connected"\)/g) || []).length, 2);
  const page = await readFile("../ochola-supernet/src/pages/admin/network/migration/NetworkMigration.tsx", "utf8");
  assert.match(page, /Verify RouterOS API/);
  assert.match(page, /Download both/);
  assert.match(page, /setCurrentStep\(2\)/);
});
